### ISSUE TITLE
NullPointerException on empty PR description

### ISSUE THREAD

**Issue by klamontagne** [Expium/ghi2jira#6]
Quick fix for anyone using this and wondering why some issues crash, Try adding a description to every "_No description provided_" PRs. (`"body": null` in the API)

**Comment by kylecordes** [comment]
Thanks! PRs wanted!

**Comment by hamednejad** [comment]
Thank you so much. This is great! 

I have a project that has 6000 tickets. The code crashes on line 129 (I think it is related to replacing # signs. Unfortunately I don't know Clojure to make the change. Is it possible for you to take a guess at what might cause the Nullpointer exception there and how to fix it? Or show me how to import a chunk of the issues one at a time?

**Comment by klamontagne** [comment]
Hello, it's possible that you hit the [API rate limit](https://developer.github.com/v3/rate_limit/) with 6000 issues. I have an alternative script in Ruby: [klamontagne/github-to-jira](https://github.com/klamontagne/github-to-jira) if you know Ruby more than Clojure. It's a bit slower but it lets the user set a range of issue numbers to work around GitHub's API rate limit.

**Comment by hamednejad** [comment]
Thank you so much! I'll look into it.

**Comment by kylecordes** [comment]
@hamednejad Were you able to get up and running by filling in a description for whichever of your PRs had none?  If you can confirm that that fixed it, I think someone (maybe me) could put in a one line fix to tolerate description:null from the API.

**Comment by hamednejad** [comment]
@kylecordes, what @klamontagne sent helped to get us going. I think there were some pull requests that didn't have any detail that were crashing this code. Would be nice if you can exclude them in your code. CSV format is definitely better for transferring the cases since you can also use it for updating the cases that are already in the repository. Other change that would be great is changing the comments format to date;commenter;comment. This will format the comment the way JIRA wants it at this point in time. Thanks again for your help.

**Comment by kylecordes** [comment]
@hamednejad Ah, glad to hear you were able to get things working with that other importer. I haven't studied it, to see if it aims to translate as many kinds of information.

About the comment format, this contribution from @botimer a few days ago, adjusted for that.

https://github.com/Expium/ghi2jira/commit/f071c79ac5f840f89cbe891b5fc872964f2527c2

About the PRs with empty description, that's a trivial fix which I'll put in in a moment.

**Comment by hamednejad** [comment]
Thank you @kylecordes . Really appreciate it.
